# Copyright 2026 Vojnar Autonomous s.r.o.
# Licensed under the Apache License, Version 2.0

import os
import re
from dataclasses import dataclass
from dataclasses import field

PREFIX_VARS = ('AMENT_PREFIX_PATH', 'CMAKE_PREFIX_PATH', 'COLCON_PREFIX_PATH')

PATHLIST_VARS = PREFIX_VARS + (
    'PATH', 'LD_LIBRARY_PATH', 'PYTHONPATH', 'PKG_CONFIG_PATH',
    'GZ_CONFIG_PATH', 'IGN_CONFIG_PATH', 'GZ_SIM_RESOURCE_PATH',
    'QT_PLUGIN_PATH', 'QML2_IMPORT_PATH')

_CHAIN_HEADER = 'extends the environment with the environment of other prefix'
_CHAIN_BEGIN = '# source chained prefixes'
_CHAIN_END = '# source this prefix'
_CHAIN_ENTRY = re.compile(r'^COLCON_CURRENT_PREFIX="([^"$]+)"\s*$')
_INSTALL_MARKER = '.colcon_install_layout'


def split_pathlist(value):
    return [v for v in value.split(os.pathsep) if v] if value else []


def canon(path):
    return os.path.realpath(path)


def is_under(path, root):
    path = canon(path)
    return path == root or path.startswith(root.rstrip(os.sep) + os.sep)


def read_chain(prefix):
    """Return chained prefixes baked into <prefix>/setup.sh.

    None means the file is missing or not generated by colcon.
    """
    try:
        with open(os.path.join(prefix, 'setup.sh'), encoding='utf-8') as f:
            lines = f.read().splitlines()
    except OSError:
        return None
    if not any(_CHAIN_HEADER in line for line in lines[:8]):
        return None
    chain, active = [], False
    for line in lines:
        if line.startswith(_CHAIN_BEGIN):
            active = True
        elif line.startswith(_CHAIN_END):
            break
        elif active:
            m = _CHAIN_ENTRY.match(line)
            if m:
                chain.append(canon(m.group(1)))
    chain.reverse()
    return chain


def chain_closure(prefix):
    seen, stack = set(), [canon(prefix)]
    while stack:
        current = stack.pop()
        for parent in read_chain(current) or []:
            if parent not in seen:
                seen.add(parent)
                stack.append(parent)
    return seen


def workspace_root_of(entry):
    entry = canon(entry)
    for candidate in (entry, os.path.dirname(entry)):
        if os.path.exists(os.path.join(candidate, _INSTALL_MARKER)):
            return candidate
    return None


@dataclass
class Plan:
    mode: str
    roots: list = field(default_factory=list)
    reasons: dict = field(default_factory=dict)
    cycles: list = field(default_factory=list)
    kept: list = field(default_factory=list)
    notes: list = field(default_factory=list)

    @property
    def empty(self):
        return not self.roots


def _all_entries(env, variables):
    for var in variables:
        for entry in split_pathlist(env.get(var, '')):
            yield var, entry


def plan_drop_self(env, install_base):
    self_root = canon(install_base)
    plan = Plan(mode='drop-self-underlay')
    colcon_prefixes = [canon(p) for p in split_pathlist(
        env.get('COLCON_PREFIX_PATH', ''))]
    present = self_root in colcon_prefixes or any(
        is_under(e, self_root) for _, e in _all_entries(env, PREFIX_VARS))
    if present:
        plan.roots.append(self_root)
        plan.reasons[self_root] = 'own install of this workspace'
    self_idx = colcon_prefixes.index(self_root) \
        if self_root in colcon_prefixes else None
    self_closure = chain_closure(self_root)

    for idx, prefix in enumerate(colcon_prefixes):
        if prefix == self_root:
            continue
        if read_chain(prefix) is not None:
            if self_root in chain_closure(prefix):
                plan.roots.append(prefix)
                plan.reasons[prefix] = 'built on top of this workspace'
                if prefix in self_closure:
                    plan.cycles.append(prefix)
        elif self_idx is not None and idx < self_idx:
            plan.roots.append(prefix)
            plan.reasons[prefix] = (
                'sourced after this workspace (order; chain unavailable)')
    return plan


def plan_clean(env, base_prefixes):
    bases = [canon(b) for b in base_prefixes]
    plan = Plan(mode='clean-underlay')
    seen = set()

    def consider(entry, force_root=False):
        if any(is_under(entry, b) for b in bases):
            return
        root = canon(entry) if force_root else workspace_root_of(entry)
        if root is None:
            if canon(entry) not in plan.kept:
                plan.kept.append(canon(entry))
            return
        if root not in seen:
            seen.add(root)
            plan.roots.append(root)
            plan.reasons[root] = 'workspace prefix outside base install'

    for entry in split_pathlist(env.get('COLCON_PREFIX_PATH', '')):
        consider(entry, force_root=True)
    for var in ('AMENT_PREFIX_PATH', 'CMAKE_PREFIX_PATH'):
        for entry in split_pathlist(env.get(var, '')):
            consider(entry)
    plan.kept = [k for k in plan.kept if k not in seen]
    return plan


def apply_plan(env, roots):
    """Strip entries under roots from path lists; return {var: (old, new)}."""
    changes = {}
    if not roots:
        return changes
    for var, value in list(env.items()):
        if os.pathsep not in value and var not in PATHLIST_VARS:
            continue
        parts = value.split(os.pathsep)
        kept = [p for p in parts
                if not (p and any(is_under(p, r) for r in roots))]
        if len(kept) == len(parts):
            continue
        new = os.pathsep.join(kept)
        changes[var] = (value, new if kept else None)
        if kept:
            env[var] = new
        else:
            del env[var]
    return changes
